// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArrowDownIcon: typeof import('./components/Icons/ArrowDownIcon.vue')['default']
    ArrowLeftIcon: typeof import('./components/Icons/ArrowLeftIcon.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseCard: typeof import('./components/BaseCard.vue')['default']
    BaseInputNumber: typeof import('./components/BaseInputNumber.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    Board: typeof import('./components/Board.vue')['default']
    BoomIcon: typeof import('./components/Icons/BoomIcon.vue')['default']
    Cell: typeof import('./components/Cell.vue')['default']
    CurrencyIcon: typeof import('./components/Icons/CurrencyIcon.vue')['default']
    DotIcon: typeof import('./components/Icons/DotIcon.vue')['default']
    ExternalLinkIcon: typeof import('./components/Icons/ExternalLinkIcon.vue')['default']
    FlagIcon: typeof import('./components/Icons/FlagIcon.vue')['default']
    Heading1: typeof import('./components/Heading1.vue')['default']
    Heading2: typeof import('./components/Heading2.vue')['default']
    InfoIcon: typeof import('./components/Icons/InfoIcon.vue')['default']
    InputSearch: typeof import('./components/InputSearch.vue')['default']
    LoadingDot: typeof import('./components/LoadingDot.vue')['default']
    LoadingIndicator: typeof import('./components/LoadingIndicator.vue')['default']
    MenuIcon: typeof import('./components/Icons/MenuIcon.vue')['default']
    MinusIcon: typeof import('./components/Icons/MinusIcon.vue')['default']
    NoData: typeof import('./components/NoData.vue')['default']
    NumberPercent: typeof import('./components/NumberPercent.vue')['default']
    NumberUnit: typeof import('./components/NumberUnit.vue')['default']
    NumberValue: typeof import('./components/NumberValue.vue')['default']
    NumberValueLowerThan: typeof import('./components/NumberValueLowerThan.vue')['default']
    NumberValueSplit: typeof import('./components/NumberValueSplit.vue')['default']
    PlusIcon: typeof import('./components/Icons/PlusIcon.vue')['default']
    Row: typeof import('./components/Row.vue')['default']
    SearchIcon: typeof import('./components/Icons/SearchIcon.vue')['default']
  }
}

export { }
